# namelist_reference.py

NAMELISTS = {
    "HEAD": {
        "version": {"type": "integer", "default": 0},
        "title": {"type": "string", "default": " "},
    },
    "TIME": {
        "print": {"type": "real", "default": 60.0},
        "simulation": {"type": "real", "default": 900.0},
        "spreadsheet": {"type": "real", "default": 15.0},
        "smokeview": {"type": "real", "default": 15.0},
    },
    "INIT": {
        "pressure": {"type": "real", "default": 101325.0},
        "relative_humidity": {"type": "real", "default": 50.0},
        "interior_temperature": {"type": "real", "default": 20.0},
        "exterior_temperature": {"type": "real", "default": 20.0},
        "interior_o2_mass_fraction": {"type": "real", "default": 0.23},
        "exterior_o2_mass_fraction": {"type": "real", "default": 0.23},
    },
    "MISC": {
        "adiabatic": {"type": "logical", "default": False},
        "max_time_step": {"type": "real", "default": 1.0},
        "max_iteration": {"type": "real", "default": -1.0},
        "lower_oxygen_limit": {"type": "real", "default": 0.15},
        "specific_extinction": {"type": "real_array", "default": [8700.0, 4400.0]},
        "overwrite": {"type": "logical", "default": True},
    },
    "MATL": {
        "conductivity": {"type": "real", "default": 0.0},
        "density": {"type": "real", "default": 0.0},
        "emissivity": {"type": "real", "default": 0.9},
        "id": {"type": "string", "default": "NULL"},
        "material": {"type": "string", "default": "NULL"},
        "specific_heat": {"type": "real", "default": 0.0},
        "thickness": {"type": "real", "default": 0.0},
        "fyi": {"type": "string", "default": " "},
    },
    "COMP": {
        "cross_sect_areas": {"type": "real_array", "default": [-1001.0]},
        "cross_sect_heights": {"type": "real_array", "default": [-1001.0]},
        "depth": {"type": "real", "default": 0.0},
        "grid": {"type": "integer_array", "default": [50, 50, 50]},
        "hall": {"type": "logical", "default": False},
        "height": {"type": "real", "default": 0.0},
        "comp_id": {"type": "string", "default": "NULL"},
        "ceiling_matl_id": {"type": "string_array", "default": ["OFF", "OFF", "OFF"]},
        "floor_matl_id": {"type": "string_array", "default": ["OFF", "OFF", "OFF"]},
        "wall_matl_id": {"type": "string_array", "default": ["OFF", "OFF", "OFF"]},
        "ceiling_thickness": {"type": "real_array", "default": [0.0, 0.0, 0.0]},
        "floor_thickness": {"type": "real_array", "default": [0.0, 0.0, 0.0]},
        "wall_thickness": {"type": "real_array", "default": [0.0, 0.0, 0.0]},
        "origin": {"type": "real_array", "default": [0.0, 0.0, 0.0]},
        "shaft": {"type": "logical", "default": False},
        "width": {"type": "real", "default": 0.0},
        "leak_area_ratio": {"type": "real_array", "default": [0.0, 0.0]},
        "leak_area": {"type": "real_array", "default": [0.0, 0.0]},
        "flow_coefficient": {"type": "real", "default": 0.07},
        "fyi": {"type": "string", "default": " "},
    },
    "DEVC": {
        "comp_id": {"type": "string", "default": "NULL"},
        "type": {"type": "string", "default": "NULL"},
        "id": {"type": "string", "default": "NULL"},
        "temperature_depth": {"type": "real", "default": 0.5},
        "depth_units": {"type": "string", "default": "FRACTION"},
        "location": {"type": "real_array", "default": [-1.0, -1.0, -0.0762]},
        "matl_id": {"type": "string", "default": "NULL"},
        "normal": {"type": "real_array", "default": [0.0, 0.0, 1.0]},
        "surface_orientation": {"type": "string", "default": "NULL"},
        "surface_temperature": {"type": "real", "default": 20.0},
        "rti": {"type": "real", "default": 50.0},
        "setpoint": {"type": "real", "default": -1001.0},
        "spray_density": {"type": "real", "default": -300.0},
        "setpoints": {"type": "real_array", "default": [-1001.0, -1001.0]},
        "adiabatic_target": {"type": "logical", "default": False},
        "convection_coefficients": {"type": "real_array", "default": [0.0, 0.0]},
        "fyi": {"type": "string", "default": " "},
    },
    "RAMP": {
        "f": {"type": "real_array", "default": [-1001.0]},
        "id": {"type": "string", "default": "NULL"},
        "t": {"type": "real_array", "default": [-1001.0]},
        "z": {"type": "real_array", "default": [-1001.0]},
        "type": {"type": "string", "default": "NULL"},
        "comp_ids": {"type": "string_array", "default": ["NULL", "NULL"]},
    },
    "TABL": {
        "id": {"type": "string", "default": "NULL"},
        "labels": {"type": "string_array", "default": ["NULL"]},
        "data": {"type": "real_array", "default": [-1001.0]},
    },
    "FIRE": {
        "comp_id": {"type": "string", "default": "NULL"},
        "devc_id": {"type": "string", "default": "NULL"},
        "fire_id": {"type": "string", "default": "NULL"},
        "id": {"type": "string", "default": "NULL"},
        "ignition_criterion": {"type": "string", "default": "TIME"},
        "location": {"type": "real_array", "default": [0.0, 0.0]},
        "setpoint": {"type": "real", "default": 0.0},
        "fyi": {"type": "string", "default": " "},
    },
    "CHEM": {
        "area": {"type": "real", "default": 0.0},
        "carbon": {"type": "real", "default": 0.0},
        "chlorine": {"type": "real", "default": 0.0},
        "co_yield": {"type": "real", "default": 0.0},
        "heat_of_combustion": {"type": "real", "default": 50000.0},
        "hcn_yield": {"type": "real", "default": 0.0},
        "hrr": {"type": "real", "default": 0.0},
        "hydrogen": {"type": "real", "default": 0.0},
        "nitrogen": {"type": "real", "default": 0.0},
        "oxygen": {"type": "real", "default": 0.0},
        "radiative_fraction": {"type": "real", "default": 0.0},
        "soot_yield": {"type": "real", "default": 0.0},
        "table_id": {"type": "string", "default": "NULL"},
        "trace_yield": {"type": "real", "default": 0.0},
        "flaming_transition_time": {"type": "real", "default": 0.0},
        "comp_id": {"type": "string", "default": "NULL"},
        "id": {"type": "string", "default": "NULL"},
    },
    "VENT": {
        "area": {"type": "real", "default": 0.0},
        "areas": {"type": "real_array", "default": [0.0, 0.0]},
        "bottom": {"type": "real", "default": 0.0},
        "comp_ids": {"type": "string_array", "default": ["NULL", "NULL"]},
        "criterion": {"type": "string", "default": "TIME"},
        "cutoffs": {"type": "real_array", "default": [200.0, 300.0]},
        "devc_id": {"type": "string", "default": "NULL"},
        "f": {"type": "real_array", "default": [-1001.0]},
        "face": {"type": "string", "default": "NULL"},
        "filter_efficiency": {"type": "real", "default": 0.0},
        "filter_time": {"type": "real", "default": 0.0},
        "flow": {"type": "real", "default": 0.0},
        "height": {"type": "real", "default": 0.0},
        "heights": {"type": "real_array", "default": [0.0, 0.0]},
        "id": {"type": "string", "default": "NULL"},
        "offset": {"type": "real", "default": 0.0},
        "offsets": {"type": "real_array", "default": [0.0, 0.0]},
        "orientations": {"type": "string_array", "default": ["VERTICAL", "VERTICAL"]},
        "pre_fraction": {"type": "real", "default": 1.0},
        "post_fraction": {"type": "real", "default": 1.0},
        "setpoint": {"type": "real", "default": 0.0},
        "shape": {"type": "string", "default": "NULL"},
        "t": {"type": "real_array", "default": [-1001.0]},
        "top": {"type": "real", "default": 0.0},
        "type": {"type": "string", "default": "NULL"},
        "width": {"type": "real", "default": 0.0},
        "fyi": {"type": "string", "default": " "},
        "flow_coefficient": {"type": "real", "default": 0.0},
    },
    "CONN": {
        "comp_id": {"type": "string", "default": "NULL"},
        "comp_ids": {"type": "string_array", "default": ["NULL", "NULL"]},
        "f": {"type": "real_array", "default": [-1001.0]},
        "type": {"type": "string", "default": "NULL"},
    },
    "ISOF": {
        "comp_id": {"type": "string", "default": "NULL"},
        "value": {"type": "real", "default": -1001.0},
    },
    "SLCF": {
        "domain": {"type": "string", "default": "NULL"},
        "plane": {"type": "string", "default": "NULL"},
        "position": {"type": "real", "default": 0.0},
        "comp_id": {"type": "string", "default": "NULL"},
    },
    "DIAG": {
        "mode": {"type": "string", "default": " "},
        "rad_solver": {"type": "string", "default": "NULL"},
        "partial_pressure_h2o": {"type": "real", "default": -1001.0},
        "partial_pressure_co2": {"type": "real", "default": -1001.0},
        "gas_temperature": {"type": "real", "default": -1001.0},
        "t": {"type": "real_array", "default": [-1001.0]},
        "f": {"type": "real_array", "default": [-1001.0]},
        "horizontal_flow_sub_model": {"type": "string", "default": "ON"},
        "fire_sub_model": {"type": "string", "default": "ON"},
        "entrainment_sub_model": {"type": "string", "default": "ON"},
        "vertical_flow_sub_model": {"type": "string", "default": "ON"},
        "ceiling_jet_sub_model": {"type": "string", "default": "ON"},
        "door_jet_fire_sub_model": {"type": "string", "default": "ON"},
        "convection_sub_model": {"type": "string", "default": "ON"},
        "radiation_sub_model": {"type": "string", "default": "ON"},
        "conduction_sub_model": {"type": "string", "default": "ON"},
        "debug_print": {"type": "string", "default": "OFF"},
        "mechanical_flow_sub_model": {"type": "string", "default": "ON"},
        "keyboard_input": {"type": "string", "default": "ON"},
        "steady_state_initial_conditions": {"type": "string", "default": "OFF"},
        "dassl_debug_print": {"type": "string", "default": "OFF"},
        "oxygen_tracking": {"type": "string", "default": "OFF"},
        "gas_absorbtion_sub_model": {"type": "string", "default": "CALCULATED"},
        "residual_debug_print": {"type": "string", "default": "OFF"},
        "layer_mixing_sub_model": {"type": "string", "default": "ON"},
        "adiabatic_target_verification": {"type": "string", "default": "OFF"},
        "radiative_incident_flux": {"type": "real", "default": 0.0},
        "upper_layer_thickness": {"type": "real", "default": -1001.0},
        "verification_time_step": {"type": "real", "default": 0.0},
        "verification_fire_heat_flux": {"type": "real", "default": -1001.0},
    },
    "DUMP": {
        "id": {"type": "string", "default": "NULL"},
        "file": {"type": "string", "default": " "},
        "first_device": {"type": "string", "default": " "},
        "first_measurement": {"type": "string", "default": " "},
        "second_device": {"type": "string", "default": " "},
        "second_measurement": {"type": "string", "default": " "},
        "first_field": {"type": "string_array", "default": [" ", " "]},
        "second_field": {"type": "string_array", "default": [" ", " "]},
        "dump_criterion": {"type": "real", "default": 0.0},
        "criterion": {"type": "string", "default": "NULL"},
        "type": {"type": "string", "default": "NULL"},
        "fyi": {"type": "string", "default": " "},
    },
}
